//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGIftCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_info
    {
        public int contactInfoNumber { get; set; }
        public int customerid { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public Nullable<int> mastercardAccepted { get; set; }
        public Nullable<int> discoverAccepted { get; set; }
        public Nullable<int> americanExpressAccepted { get; set; }
        public Nullable<int> visaAccepted { get; set; }
        public Nullable<int> allowGratuity { get; set; }
        public Nullable<int> allowMailOption { get; set; }
        public Nullable<double> shippingCost { get; set; }
        public Nullable<int> expireAfterDays { get; set; }
        public string finePrint { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
