//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGIftCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.contact_info = new HashSet<contact_info>();
            this.giftcards = new HashSet<giftcard>();
        }
    
        public int customerNumber { get; set; }
        public string customerName { get; set; }
        public string password { get; set; }
        public Nullable<int> logoUploaded { get; set; }
    
        public virtual ICollection<contact_info> contact_info { get; set; }
        public virtual ICollection<giftcard> giftcards { get; set; }
    }
}
