//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGIftCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftcard
    {
        public int giftcardNumber { get; set; }
        public int customerid { get; set; }
        public string giftcardMessage { get; set; }
        public string giftcardRecipient { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
